AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true

  MyPublicSubnet1A:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: us-east-1a
      CidrBlock: '10.0.0.0/24'

  MyPublicSubnet1B:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: us-east-1b
      CidrBlock: '10.0.1.0/24'

  MyPrivateSubnet1A:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: us-east-1a
      CidrBlock: '10.0.2.0/24'

  MyInternetGateway:
    Type: 'AWS::EC2::InternetGateway'

  MyGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  MyPublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref MyVPC

  MyPublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: MyGatewayAttachment
    Properties:
      RouteTableId: !Ref MyPublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref MyInternetGateway

  MyPrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref MyVPC

  MyPrivateRoute1A:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref MyPrivateRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId: !Ref MyNatGateway1A

  MyNatGateway1A:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt MyEIP1A.AllocationId
      SubnetId: !Ref MyPublicSubnet1A

  MyEIP1A:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: 'vpc'

Outputs:
  VPCId:
    Value: !Ref MyVPC
  PublicSubnet1AId:
    Value: !Ref MyPublicSubnet1A
  PublicSubnet1BId:
    Value: !Ref MyPublicSubnet1B
  PrivateSubnet1AId:
    Value: !Ref MyPrivateSubnet1A
  InternetGatewayId:
    Value: !Ref MyInternetGateway
  PublicRouteTableId:
    Value: !Ref MyPublicRouteTable
  PrivateRouteTableId:
    Value: !Ref MyPrivateRouteTable
  NatGateway1AId:
    Value: !Ref MyNatGateway1A
  EIP1A:
    Value: !Ref MyEIP1A
