AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Creating ECS service
Globals:
  Function:
    Timeout: 15
Parameters:
  Version:
    Type: String
    Default: v1
  ServiceName:
    Type: String
    Default: devs-withmission
  AppName:
    Type: String
    Description: Name of app requiring ELB exposure
    Default: devs-with-mission-web
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - prd
      - dev
    Description: definicao ambiente
Mappings:
  ImageMap:
    us-east-1:
      dev: '024177866594.dkr.ecr.us-east-1.amazonaws.com/devs-with-mission:latest'
  VpcMap:
    us-east-1:
      dev: vpc-0eb3f4f2e5bc27896
  NetworkLoadBalancerSecurityGroupMap:
    us-east-1:
      dev: sg-0ad5aff4d1389609e
  FargateHtppSecurityGroupMap:
    us-east-1:
      dev: sg-0ad5aff4d1389609e
  PrivateSubnetMapAZ:
    us-east-1:
      dev: subnet-0e14f7e0458f8fff4
  PublicSubnetMapAZ:
    us-east-1:
      dev: subnet-01bcca6490e257468
  AvailabilityZone1:
    us-east-1:
      dev: us-east-1a
  AvailabilityZone2:
    us-east-1:
      dev: us-east-1b
  ApplicationEnvironmentMap:
    us-east-1:
      dev: dev
  FargateNodes:
    us-east-1:
      dev: '2'
  ListenerPortMap:
    us-east-1:
      dev: '8080'
Resources:
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      IpAddressType: ipv4
      Name: !Sub '${ServiceName}-alb-${Stage}'
      Scheme: internal
      Type: application
      SecurityGroups:
        - !FindInMap 
          - FargateHtppSecurityGroupMap
          - !Ref 'AWS::Region'
          - !Ref Stage
      Subnets:
        - !FindInMap 
          - PrivateSubnetMapAZ
          - !Ref 'AWS::Region'
          - !Ref Stage
        - !FindInMap 
          - PublicSubnetMapAZ
          - !Ref 'AWS::Region'
          - !Ref Stage
      Tags:
        - Key: Ambiente
          Value: !Ref Stage
        - Key: Name
          Value: !Ref AppName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 92f2a9d7-fbb1-4463-93ec-1322cd8a9552
  Cluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub '${AppName}-${Stage}'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Ambiente
          Value: !Ref Stage
        - Key: Name
          Value: !Ref AppName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4b66c44c-855e-4ade-97dd-d105bff92800
  Policy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - 's3:*'
              - 'ecs:*'
              - 'ecr:*'
              - 'logs:*'
            Resource: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e23115c9-283b-4b36-a8a6-5d0b6caf60d3
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref Policy
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0218e1f7-9d93-461b-98e7-8960407e08e0
  EcsLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/ecs/${ServiceName}-${Stage}'
      RetentionInDays: 30
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6228f705-21d4-4d9f-ad37-124c8d73c0c5
  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Image: !FindInMap 
            - ImageMap
            - !Ref 'AWS::Region'
            - !Ref Stage
          Cpu: 512
          Memory: 1024
          MemoryReservation: 512
          Name: !Sub '${ServiceName}_container'
          PortMappings:
            - HostPort: 3000
              Protocol: tcp
              ContainerPort: 3000
          Essential: true
          Environment:
            - Name: ENV
              Value: dev
            - Name: PORT
              Value: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref EcsLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
      Cpu: '512'
      Memory: '1024'
      Family: !Ref AppName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref Role
      TaskRoleArn: !Ref Role
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f8696e5b-3387-4c24-a292-1cb3256306e9
  Service:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref Cluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: !FindInMap 
        - FargateNodes
        - !Ref 'AWS::Region'
        - !Ref Stage
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: !Sub '${ServiceName}_container'
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !FindInMap 
              - FargateHtppSecurityGroupMap
              - !Ref 'AWS::Region'
              - !Ref Stage
          Subnets:
            - !FindInMap 
              - PrivateSubnetMapAZ
              - !Ref 'AWS::Region'
              - !Ref Stage
            - !FindInMap 
              - PublicSubnetMapAZ
              - !Ref 'AWS::Region'
              - !Ref Stage
      PlatformVersion: LATEST
      ServiceName: !Sub '${ServiceName}_${Stage}'
      TaskDefinition: !Ref TaskDefinition
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3138747b-5fd7-45a7-ad29-27fbe470234b
    DependsOn:
      - LoadBalancer
Metadata:
  'AWS::CloudFormation::Designer':
    6228f705-21d4-4d9f-ad37-124c8d73c0c5:
      size:
        width: 150
        height: 150
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    e23115c9-283b-4b36-a8a6-5d0b6caf60d3:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 90
      z: 1
      embeds: []
    0218e1f7-9d93-461b-98e7-8960407e08e0:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 210
      z: 1
      embeds: []
      isassociatedwith:
        - e23115c9-283b-4b36-a8a6-5d0b6caf60d3
    f8696e5b-3387-4c24-a292-1cb3256306e9:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 300
      z: 1
      embeds: []
    4b66c44c-855e-4ade-97dd-d105bff92800:
      size:
        width: 60
        height: 60
      position:
        x: 390
        'y': 90
      z: 1
      embeds: []
    92f2a9d7-fbb1-4463-93ec-1322cd8a9552:
      size:
        width: 60
        height: 60
      position:
        x: 390
        'y': 210
      z: 1
      embeds: []
    3138747b-5fd7-45a7-ad29-27fbe470234b:
      size:
        width: 60
        height: 60
      position:
        x: 420
        'y': 330
      z: 1
      embeds: []
      dependson:
        - 92f2a9d7-fbb1-4463-93ec-1322cd8a9552
    940ff9ba-5d2b-4fea-a50d-b63db2b0bc61:
      source:
        id: 3138747b-5fd7-45a7-ad29-27fbe470234b
      target:
        id: 92f2a9d7-fbb1-4463-93ec-1322cd8a9552
      z: 11
