name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop, feature ]
jobs:


  build:
    
    name: Deploy website
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g2k0a1o0
        docker build -t devs-with-misison .
        docker tag devs-with-misison:latest public.ecr.aws/g2k0a1o0/devs-with-misison:latest
        docker push public.ecr.aws/g2k0a1o0/devs-with-misison:latest
   
 

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Terraform Init
      run: terraform init
      working-directory: Infra/terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: Infra/terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -input=false tfplan
      working-directory: Infra/terraform
